let userData = [
    {
        id: 1,
        username: "soleh",
        email:" nursoleh33@gmail.com",
        age: 24,
        marriage: true,
    },
    {   id: 2,
        username: "alex",
        email:" nursoleh22@gmail.com",
        age: 28,
        marriage: false,
    },
    {
        id: 3,
        username: "alex",
        email:" nurmuhamadsoleh42@gmail.com",
        age: 26,
        marriage: true,
    },
    {
        id: 4,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
    {
        id: 5,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
    {
        id: 6,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
    {
        id: 7,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
    {
        id: 8,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
    {
        id: 9,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
    {
        id: 10,
        username: "dwi",
        email:" dwipuspita@gmail.com",
        age: 24,
        marriage: true,
    },
];
export default userData;